# 项目相关配置
system:
  # 项目名称
  name: initializr-modules
  # 开发者
  developer: 张庆福
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020

server:
  # 开启优雅停机,默认IMMEDIATE是立即关机
  shutdown: graceful
  servlet:
    # 项目路径
    context-path: /initializr

spring:
  profiles:
    # 指定运行环境
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # jackson时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  lifecycle:
    # 缓冲时间,默认时间为30S,意味着最多等待30S，超时无论线程任务是否执行完毕都会停机处理，一定要合理合理设置。
    timeout-per-shutdown-phase: 30s

mybatis-plus:
  # 指定Mapper.xml文件位置,可以是数组.默认配置为'- classpath*:/mapper/**/*.xml'
  mapperLocations:
    - classpath*:/mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  typeAliasesPackage: com.yese.entity
  global-config:
    db-config:
      # 配置逻辑删除相关
      # 全局逻辑删除的实体字段名(根据实际情况配置)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

# actuator相关
management:
  endpoint:
    shutdown:
      # 启用shutdown
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      # 自定义管理端点的前缀(保证安全),http://127.0.0.1:40000/MyActuator/shutdown
      base-path: /MyActuator
  server:
    # 自定义端口
    port: 40000
    # 不允许远程管理连接(不允许外部调用保证安全)
    address: 127.0.0.1